### ISSUE TITLE
Investigate and fix the validation issues

### ISSUE THREAD

**Issue by naveedkhan8067** [iTwin/bis-schemas#405]
1. Failure message in imodel schema validation mixed with the validation summary. 

```
> LinearReferencing.02.00.03
Error: Failing the tool because a validation has failed.
at getResults (D:\a\1\s\node_modules\@bentley\imodel-schema-validator\lib\iModelSchemaValidator.js:277:15)
at validateReleasedSchemas (D:\a\1\s\tools\SchemaValidation\iModelSchemaValidationRunner.js:138:3)
at async validateIModelSchemas (D:\a\1\s\tools\SchemaValidation\iModelSchemaValidationRunner.js:71:7)
> Schema validation against BIS rules <passed>
> Schema content verification <passed>
> Released schema is approved and verified <passed>
```

**Comment by naveedkhan8067** [comment]
Note: I was able to see the first issue (mixed error message with summary) only with our build pipelines, locally its working fine
